### ISSUE TITLE
PinPlus only opens sometimes

### ISSUE THREAD

**Issue by jeremycherfas** [vitorgalvao/pinplus#2]
Hi. I really like pinplus and the Alfred workflow; makes my life much easier except for one thing. If I use `pa` then sometimes I get the pinplus window and other times absolutely nothing happens that I can see.

If I use `ctrl-shift-alt-p` which is the shortcut I assigned, then it does automatically add the url as an unread item, but I have to go in and edit the tags etc.

I'm not sure what the problem might be. Is there another way to launch the app, not through Alfred. Maybe I could make a shortcut for that. Or maybe you already have one.

Thanks

**Comment by vitorgalvao** [comment]
Thank you for the kind words, and for opening the bug report. I also noticed that happening lately, after upgrading to Mojave (I only did so recently). It was on my list to look into, but knowing someone else is using it and missing it gave me the motivation to do it sooner!

It should now be fixed. I haven’t done extensive testing, so if you still see the issue happening, please do comment again. I will ask that you restart your machine before doing so, just to be doubly sure.

You can fetch the new version from [the releases page](https://github.com/vitorgalvao/pinplus/releases), or run `:pinplusupdateapp` in Alfred.

Thank you again.

**Comment by jeremycherfas** [comment]
Thank you Vitor

I will continue to use it and let you know if I encounter any further difficulties.

Jeremy
