### ISSUE TITLE
The application “PinPlus.app” can’t be opened.

### ISSUE THREAD

**Issue by mrmartineau** [vitorgalvao/pinplus#5]
I get this error message in the below popup when trying to run the app. Let me know if there's anything I can do to test/debug this for you.

<img width="474" alt="image" src="https://user-images.githubusercontent.com/64883/83424107-e0c46780-a423-11ea-8ac9-1cb00919c400.png">

```sh
❯ npx envinfo

  System:
    OS: macOS 10.15.4
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
    Memory: 22.16 GB / 64.00 GB
    Shell: 3.1.2 - /usr/local/bin/fish
  Binaries:
    Node: 10.20.1 - /var/folders/mk/06g84ks148s28yyss_2tcly00000gn/T/fnm-shell-8980500/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.4 - /var/folders/mk/06g84ks148s28yyss_2tcly00000gn/T/fnm-shell-8980500/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    Homebrew: 2.2.16 - /usr/local/bin/brew
    pip3: 20.1 - /usr/local/bin/pip3
    RubyGems: 3.0.3 - /usr/bin/gem
  Utilities:
    Make: 3.81 - /usr/bin/make
    GCC: 4.2.1 - /usr/bin/gcc
    Git: 2.26.2 - /usr/local/bin/git
    Clang: 1103.0.32.62 - /usr/bin/clang
    FFmpeg: 4.2.2 - /usr/local/bin/ffmpeg
  Servers:
    Apache: 2.4.41 - /usr/sbin/apachectl
    Nginx: 1.17.10 - /usr/local/bin/nginx
  Virtualization:
    VirtualBox: 6.1.6 - /usr/local/bin/vboxmanage
  IDEs:
    Nano: 2.0.6 - /usr/bin/nano
    Sublime Text: Build 3211
    VSCode: 1.45.1 - /usr/local/bin/code
    Vim: 8.1 - /usr/bin/vim
    Xcode: /undefined - /usr/bin/xcodebuild
  Languages:
    Bash: 3.2.57 - /bin/bash
    Perl: 5.18.4 - /usr/bin/perl
    PHP: 7.3.11 - /usr/bin/php
    Python: 2.7.16 - /usr/bin/python
    Python3: 3.7.7 - /usr/local/bin/python3
    Ruby: 2.6.3 - /usr/bin/ruby
  Databases:
    SQLite: 3.28.0 - /usr/bin/sqlite3
  Browsers:
    Chrome: 83.0.4103.61
    Edge: 81.0.416.68
    Firefox: 76.0.1
    Firefox Developer Edition: 77.0
    Safari: 13.1
```

**Comment by vitorgalvao** [comment]
Right click it and pick “Open”. Does that work?

**Comment by mrmartineau** [comment]
@vitorgalvao no, I'm afraid not.

**Comment by vitorgalvao** [comment]
Can you do a Get Info on it? How did you download the application?

**Comment by mrmartineau** [comment]
I downloaded the app from the releases page in this repo. Here's the get info you asked for.
![image](https://user-images.githubusercontent.com/64883/83525677-37da4300-a4dd-11ea-9145-ebf0ffce57b1.png)

**Comment by mrmartineau** [comment]
@vitorgalvao ok, so I don't know why I didn't try this before, but I cloned the repo and built the app from the latest on `master` and **it works**.. I don't know why, but I see that there is [one difference](https://github.com/vitorgalvao/pinplus/compare/1.1.6...master) between `master` and the `1.1.6` release and it doesn't involve any changes to the app itself. I guess I can close this now, but it would be useful to know why it wasn't working from the download on the releases page

**Comment by vitorgalvao** [comment]
> it would be useful to know why it wasn't working from the download on the releases page

Agreed. My bet is the fault is Catalina’s. But since I’ll never install it unless I’m forced, I can’t confirm.

**Comment by mrmartineau** [comment]
It could be Catalina, but I reckon that when I installed the dependencies, one or a few of them may have been installed more recent versions of some packages. It all depends on the semver ranges in the `package.json` of your dependencies. Perhaps you could cut a new release with updated dependencies and see if that resolves the issue..

**Comment by vitorgalvao** [comment]
Unfortunately, Electron keeps changing crap around with every release, and keeping up with that is an unpaid and unfun full time job.

I just tried to to update the dependencies, and while the app still works, stuff gets shoved out of place for essentially no reason.

I’ll take a PR to fix it or may take another look if enough people bump into your problem, but otherwise I can’t afford the time commitment to look into it right now.
